### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by repeatedly**
First 4.0.0 release

### CODE REVIEW

**Comment by repeatedly** [comment]
@ashie Could you check `centos-7-aarch64` build works or not?  `centos-8-aarch64` is succeeded but 7 is not.

**Comment by repeatedly** [comment]
In addition, rdkafka build is broken on CentOS 8. CentOS 7 and other deb packages has no rdkafka build problem.

**Comment by repeatedly** [comment]
Working on deb package release...

**Comment by hrw** [comment]
Finally some CI used ;D

**Comment by repeatedly** [comment]
Ubuntu focal / bionic and amazon linux 2 are published.

https://toolbelt.treasuredata.com/sh/install-ubuntu-bionic-td-agent4.sh
https://toolbelt.treasuredata.com/sh/install-ubuntu-focal-td-agent4.sh
https://toolbelt.treasuredata.com/sh/install-amazon2-td-agent4.sh

Ubuntu xenial and Debian buster will be published soon.

**Comment by ashie** [comment]
> In addition, rdkafka build is broken on CentOS 8. CentOS 7 and other deb packages has no rdkafka build problem.

It's reproduced on my env, td-agent-4.0.0-1.el8.x86_64.rpm contains opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/librdkafka.so but the file size is 0.

**Comment by ashie** [comment]
> It's reproduced on my env, td-agent-4.0.0-1.el8.x86_64.rpm contains opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/librdkafka.so but the file size is 0.

4.0.0rc1 uses rdkafka-0.7.0, it has valid ELF binary: 

```
$ file opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.7.0/ext/librdkafka.so 
opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.7.0/ext/librdkafka.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=487fdfa7f54efb5e87c060b36a17d6ba234e478e, stripped
```

**Comment by ashie** [comment]
> @ashie Could you check `centos-7-aarch64` build works or not? `centos-8-aarch64` is succeeded but 7 is not.

I've got the following error on building Docker container.
Probably the yum repository seems broken temporarily.

```
--> Finished Dependency Resolution
Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
           Requires: /opt/rh/rh-ruby24/root/usr/bin/ruby
Error: Package: rh-ruby24-rubygem-rdoc-5.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-runtime
Error: Package: rh-ruby24-rubygem-rdoc-5.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-ruby(release)
Error: Package: rh-ruby24-rubygem-rdoc-5.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-rubygem(io-console) >= 0.4.6
Error: Package: rh-ruby24-rubygem-rake-12.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: /opt/rh/rh-ruby24/root/usr/bin/ruby
Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-runtime
Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-ruby(release)
Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-rubygem(openssl) >= 2.0.9
Error: Package: rh-ruby24-rubygem-bundler-1.13.7-1.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-runtime
Error: Package: rh-ruby24-rubygem-bundler-1.13.7-1.el7.noarch (centos-sclo-rh)
           Requires: /opt/rh/rh-ruby24/root/usr/bin/ruby
Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-rubygem(psych) >= 2.2.2
Error: Package: rh-ruby24-rubygem-rake-12.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-runtime
Error: Package: rh-ruby24-ruby-irb-2.4.6-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-runtime
Error: Package: rh-ruby24-rubygem-rake-12.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-ruby(release)
Error: Package: rh-ruby24-rubygem-rdoc-5.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: /opt/rh/rh-ruby24/root/usr/bin/ruby
Error: Package: rh-ruby24-ruby-irb-2.4.6-92.el7.noarch (centos-sclo-rh)
           Requires: /opt/rh/rh-ruby24/root/usr/bin/ruby
Error: Package: rh-ruby24-ruby-irb-2.4.6-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-ruby-libs = 2.4.6
Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-rubygem(io-console) >= 0.4.6
Error: Package: rh-ruby24-rubygem-bundler-1.13.7-1.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-ruby(release)
Error: Package: rh-ruby24-rubygem-rdoc-5.0.0-92.el7.noarch (centos-sclo-rh)
           Requires: rh-ruby24-rubygem(json) >= 2.0.4
```

**Comment by ashie** [comment]
> > In addition, rdkafka build is broken on CentOS 8. CentOS 7 and other deb packages has no rdkafka build problem.
> 
> It's reproduced on my env, td-agent-4.0.0-1.el8.x86_64.rpm contains opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/librdkafka.so but the file size is 0.

td-agent-gem in td-agent-4.0.0-1.el8 can build valid ELF binary for rdkafka-0.8.0.

**Comment by ashie** [comment]
> > It's reproduced on my env, td-agent-4.0.0-1.el8.x86_64.rpm contains opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/librdkafka.so but the file size is 0.

Hmm, it's weird.
It's already 0 bytes just after succeeded to install:

```
/opt/td-agent/bin/gem install --no-document --bindir /root/rpmbuild/BUILDROOT/td-agent-4.0.0-1.el8.x86_64/opt/td-agent/bin /root/rpmbuild/BUILD/td-agent-4.0.0/td-agent/downloads/plugin_gems/16-rdkafka-0.8.0.gem
Fetching mini_portile2-2.5.0.gem
Fetching ffi-1.13.1.gem
Successfully installed mini_portile2-2.5.0
Building native extensions. This could take a while...
Successfully installed ffi-1.13.1
Building native extensions. This could take a while...
Successfully installed rdkafka-0.8.0
3 gems installed
ls -l /root/rpmbuild/BUILDROOT/td-agent-4.0.0-1.el8.x86_64/opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext/
total 8
-rw-r--r-- 1 root root  386 Jul  3 05:55 README.md
-rw-r--r-- 1 root root 2934 Jul  3 05:55 Rakefile
-rwxr-xr-x 1 root root    0 Jul  3 05:56 librdkafka.so
cat /root/rpmbuild/BUILDROOT/td-agent-4.0.0-1.el8.x86_64/opt/td-agent/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/rdkafka-0.8.0/gem_make.out
current directory: /root/rpmbuild/BUILDROOT/td-agent-4.0.0-1.el8.x86_64/opt/td-agent/lib/ruby/gems/2.7.0/gems/rdkafka-0.8.0/ext
/opt/td-agent/bin/ruby -I/opt/td-agent/lib/ruby/2.7.0/rubygems -rrubygems /opt/td-agent/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake RUBYARCHDIR\=/root/rpmbuild/BUILDROOT/td-agent-4.0.0-1.el8.x86_64/opt/td-agent/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/rdkafka-0.8.0 RUBYLIBDIR\=/root/rpmbuild/BUILDROOT/td-agent-4.0.0-1.el8.x86_64/opt/td-agent/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/rdkafka-0.8.0

Extracting v1.4.0 into tmp/x86_64-redhat-linux/ports/librdkafka/1.4.0... OK
Running 'configure' for librdkafka 1.4.0... OK
Running 'compile' for librdkafka 1.4.0... OK
Running 'install' for librdkafka 1.4.0... OK
```

**Comment by ashie** [comment]
> Hmm, it's weird.
> It's already 0 bytes just after succeeded to install:

It seems parallel build issue.
I can build a valid so file when I remove `MAKEFLAGFS`:

```diff
diff --git a/td-agent/Rakefile b/td-agent/Rakefile
index 0c98cbd..5dfb11b 100755
--- a/td-agent/Rakefile
+++ b/td-agent/Rakefile
@@ -651,7 +651,7 @@ class BuildTask

     makeflags = ENV["MAKEFLAGS"]
     gem_home  = ENV["GEM_HOME"]
-    ENV["MAKEFLAGS"] = "-j#{Etc.nprocessors}"
+    #ENV["MAKEFLAGS"] = "-j#{Etc.nprocessors}"
     ENV["GEM_HOME"]  = gem_staging_dir

     sh(gem_command, "install",
@@ -660,7 +660,7 @@ class BuildTask
        gem_path)

     ENV["GEM_HOME"]  = gem_home
-    ENV["MAKEFLAGS"] = makeflags
+    #ENV["MAKEFLAGS"] = makeflags
   end

   def install_gems(files)
```

**Comment by repeatedly** [comment]
Hmm... it's weird behaviour.
Can we disable parallel build on only rdkafka gem?

**Comment by ashie** [comment]
> 
> 
> Hmm... it's weird behaviour.
> Can we disable parallel build on only rdkafka gem?

I've committed it just now.

**Comment by repeatedly** [comment]
Thanks, I confirmed. Try to release centos 8 rpm.

**Comment by ashie** [comment]
> > @ashie Could you check `centos-7-aarch64` build works or not? `centos-8-aarch64` is succeeded but 7 is not.
> 
> I've got the following error on building Docker container.
> Probably the yum repository seems broken temporarily.
> 
> ```
> --> Finished Dependency Resolution
> Error: Package: rh-ruby24-rubygems-2.6.14.4-92.el7.noarch (centos-sclo-rh)
>            Requires: /opt/rh/rh-ruby24/root/usr/bin/ruby
> ...
> ```

There is no reason to use older ruby for running the build system, it doesn't affect to the target Ruby.
I'm now confirming that we can use rh-ruby26 for it.

**Comment by ashie** [comment]
> > @ashie Could you check `centos-7-aarch64` build works or not? `centos-8-aarch64` is succeeded but 7 is not.

@repeatedly  I've fixed it. Please retry.

**Pull request merged**
