### PR TITLE
Find and copy libstdc++-6.dll from building system

### PR DESCRIPTION
**Pull request by cosmo0920**
This will be fixing #98.

And this patch is inspired by https://github.com/treasure-data/omnibus-td-agent/blob/05a1f1a43732383828f4cbec47e393773c14acea/config/software/ruby.rb#L296-L323.

### CODE REVIEW

**Comment by cosmo0920** [comment]
And after merging this PR, td-agent-builder requests to use Ruby 2.4 or later which is installed by RubyInstaller2 based installer on Windows. Should we add this description in README?

**Comment by ashie** [comment]
I think it's not but for the first aid.
In the future I want to resolve it more properly:

* Remove C++ dependency from winevt_c
  * It's not using so many C++ code, can be replaced with pure C easily.
* Detect other dependent libraries automatically

**Comment by cosmo0920** [comment]
>     * Detect other dependent libraries automatically if they exist

For MSYS2, we can use this gemspec metadata:
https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#-msys2-library-dependency
We should use this metadata if depending non-bundled dynamic libraries.

**Comment by cosmo0920** [comment]
I decided that this PR should be merged but after works should replace this "first aid".

**Pull request merged**
