### PR TITLE
Install/Uninstall fluentdwinsvc service

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by ashie** [comment]
Maybe you need to add td-agent.bat to td-agent/msiexclude-files.xslt to exclude from auto picking up.

**Comment by kenhys** [comment]
```
[?25h[?25lC:\Program Files (x86)\WiX Toolset v3.11\bin\light -nologo -ext WixUIExtension -[?25h[?25l
cultures:en-us -loc localization-en-us.wxl project-files.wixobj source.wixobj -o[?25h[?25l
ut c:/td-agent-builder/td-agent/msi//repositories/td-agent-4.0.0~rc1-x64.msi    [25;77H[?25h[?25l[?25h[?25l
[80X[80C
[?25h[?25lC:\td-agent-4.0.0~rc1\td-agent\msi\source.wxs(52) : error LGHT0231 : The compone[?25h[?25l
nt 'TDAgentBat' has a key file with path 'TARGETDIR\opt\td-agent\bin\td-agent.ba[?25h[?25l
t'.  Since this path is not rooted in one of the standard directories (like Prog[?25h[?25l
ramFilesFolder),[64X[64C[25;17H[?25h[?25l this component does not fit the criteria for having an automati[?25h[?25l
cally generated guid.  (This error may also occur if a path contains a likely st[?25h[?25l
andard directory such as nesting a directory with name "Common Files" under Prog[?25h[?25l
ramFilesFolder.)[64X[64C
```

exclude pattern is wrong?

**Comment by kenhys** [comment]
failed to start service, need to investigate.
image

**Comment by kenhys** [comment]
Only `--reg-winsvc i` in `Arguments`. then failed.

image

**Comment by kenhys** [comment]
Used in `--reg-winsvc i --reg-winsvc-fluentdopt '-c c:\opt\td-agent\etc\td-agent\td-agent.conf -o c:\opt\td-agent\td-agent.log'` `Arguments`, also failed.

https://github.com/fluent-plugins-nursery/td-agent-builder/pull/122#issuecomment-651482992
image

**Comment by kenhys** [comment]
* --reg-winsvc i with Start=demand: failed to install(rollback)
* --reg-winsvc i with Start=disabled: failed to install(rollback)
* --reg-winsvc i --reg-winsvc-fluentdopt '-c c:/FULLPATH_TO...'  : failed to install(rollback)
* --reg-winsvc i --reg-winsvc-fluentdopt '-c c:/FULLPATH_TO \\\\ ESCAPE...'  : failed to install(rollback)
* --reg-winsvc i --reg-winsvc-fluentdopt "-c c:/FULLPATH_TO \\\\ ESCAPE..."  : failed to install(rollback)

**Comment by kenhys** [comment]
Attach `--reg-winsvc i` logging result with /l*vx log.txt

[log.reg-winsvc-i.txt](https://github.com/fluent-plugins-nursery/td-agent-builder/files/4849263/log.reg-winsvc-i.txt)

**Comment by kenhys** [comment]
Attached log says:

```
MSI (s) (94:B0) [12:11:09:277]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
MSI (s) (94:B0) [12:11:09:277]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (94:B0) [12:11:09:277]: Executing op: ServiceInstall(Name=fluentdwinsvc,DisplayName=Fluentd Windows Service,ImagePath=C:\opt\td-agent\bin\td-agent-service.bat --reg-winsvc i ,ServiceType=16,StartType=3,ErrorControl=1,,Dependencies=[~],,,Password=**********,Description=Fluentd is an event collector system.,,)
MSI (s) (94:B0) [12:11:09:277]: Executing op: ActionStart(Name=StartServices,Description=Starting services,Template=Service: [1])
MSI (s) (94:B0) [12:11:09:277]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (94:B0) [12:11:09:277]: Executing op: ServiceControl(,Name=fluentdwinsvc,Action=1,,)
MSI (s) (94:B0) [12:12:06:090]: Note: 1: 2205 2:  3: Error 
MSI (s) (94:B0) [12:12:06:090]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1920 
MSI (c) (10:78) [12:12:06:090]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial
```

https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-error-messages

2205 | Database: [2]. Table does not exist: [3].
2228 | Database: [2]. Unknown table '[3]' in SQL query: [4].

**Comment by kenhys** [comment]
https://github.com/kenhys/wixtoolset-examples use `InstallExecuteSequence` and collected log by msiexec service.msi `/l*vx`.
[retry.utf8.txt](https://github.com/fluent-plugins-nursery/td-agent-builder/files/4861668/retry.utf8.txt)

**Comment by kenhys** [comment]
It works as expected to install service.

image

**Comment by cosmo0920** [comment]
I'm building msi packge with this branch....

**Pull request merged**
