### PR TITLE
Use appropriate Gemfile on each environment

### PR DESCRIPTION
**Pull request by kenhys**
In the previous version, installed gem may not be guaranteed on
build time because bundler automultiplatform is not fully supported
yet. (We need bundler 2.2.0 not released yet)

This commit fixes this issue by using separated Gemfile for each
environment.

Closes: #152

### CODE REVIEW

**Comment by kenhys** [comment]
I'll do it.

**Comment by kenhys** [comment]
I've updated README.md

**Comment by cosmo0920** [comment]
> Should we write down the new dependent gems installation processes?
> Top Gemfile does not exist. So, we should change descriptions for installation procedures in README.
> I'd fallen this pitfall. cry

I mean that when start to use separated Gemfile, users must specify gemfile location with `--gemfile` option by bundler.
Just `bundle install` execution does not work.

**Comment by cosmo0920** [comment]
So, `bundle install --gemfile /path/to/gemfile` should be added in README.

**Pull request merged**
