### PR TITLE
Release 4.1.0

### PR DESCRIPTION
**Pull request by repeatedly**
For fluentd v1.12 and newer ruby/plugin versions.

### CODE REVIEW

**Comment by repeatedly** [comment]
I tried to build centos-8 and ubuntu-bionic but it failed.

- centos-8: powertools related error
- ubuntu-bionic: `gpg --keyserver`  related error

Is this environment issue or recent changes introduce this error for docker based build?

**Comment by ashie** [comment]
>     * centos-8: powertools related error

I got the same error with existing docker image.
I've resolved it by removing older image:

```console
$ docker image rm td-agent-centos-8
```

It seems that older image requires capitalized repository name "PowerTools" but new one requires "powertools".

**Comment by ashie** [comment]
> ubuntu-bionic: gpg --keyserver related error

I can't reproduce on my environment.
Could you try to remove old image?

```console
$ docker image rm td-agent-ubuntu-focal
```

**Comment by ashie** [comment]
CI failed on windows: https://github.com/fluent-plugins-nursery/td-agent-builder/pull/248/checks?check_run_id=1661917936

```
 Resolving dependencies...........
, stderr: Bundler could not find compatible versions for gem "win32-service":
  In Gemfile:
    win32-service (= 2.2.0) x64-mingw32

    fluentd x64-mingw32 was resolved to 1.12.0, which depends on
      win32-service (~> 2.1.5)
)
```

**Comment by repeatedly** [comment]
I'm now trying the build with newer images.
And I have pushed the fix for `win32-service` version issue. Next failure is caused by serverspec. Maybe, `Gemfile.lock` should be generated on Windows environment?

**Comment by kenhys** [comment]
There is no need to regenerate because we migrated bundler 2.2.x.
I'll look into it.

**Comment by kenhys** [comment]
I got it, it seems that multiple version of rake is fetched. then the old version is checked with serverspec.

**Comment by kenhys** [comment]
> I got it, it seems that multiple version of rake is fetched. then the old version is checked with serverspec.

I'm trying to do whether it is reproducible on my local build environment.

**Comment by kenhys** [comment]
> I'm trying to do whether it is reproducible on my local build environment.

Under td-agent/downloads directory, only rake 13.0.3 gem is fetched. it is expected behaviour on windows.

**Comment by kenhys** [comment]
> Under td-agent/downloads directory, only rake 13.0.3 gem is fetched. it is expected behaviour on windows.

According to build log, only rake 13.0.3 was installed, but 13.0.1 is cached (C:/opt/td-agent/lib/ruby/gems/2.7.0/cache)

**Comment by kenhys** [comment]
Related to this issue, I've found a bug of specinfra gems to detect installed gems.

**Comment by kenhys** [comment]
> Related to this issue, I've found a bug of specinfra gems to detect installed gems.

I've sent PR to fix a bug in the specinfra side.

**Comment by ashie** [comment]
> I've sent PR to fix a bug in the specinfra side.

https://github.com/mizzy/specinfra/pull/726

**Comment by kenhys** [comment]
I'm also checking CentOS 7 error case.

**Comment by kenhys** [comment]
Manually setup td-agent/yum/serverspec-test.sh equivalent zookeeper then it returns imok. It is not reproducible yet.



```
$ echo ruok | nc localhost 2181
[2021-01-13 05:58:28,376] INFO Processing ruok command from /0:0:0:0:0:0:0:1:54962 (org.apache.zookeeper.server.NIOServerCnxn)
imok
```

```
$ rpm -qa | grep  confluent-
confluent-schema-registry-6.0.1-1.noarch
confluent-common-6.0.1-1.noarch
confluent-ksqldb-6.0.1-1.noarch
confluent-kafka-rest-6.0.1-1.noarch
confluent-community-2.13-6.0.1-1.noarch
confluent-rest-utils-6.0.1-1.noarch
confluent-kafka-6.0.1-1.noarch
```

**Comment by kenhys** [comment]
mizzy/specinfra#726 was merged, so windows CI will pass.

**Comment by kenhys** [comment]
rerun Windows CI again.

**Comment by kenhys** [comment]
> rerun Windows CI again.

Windows CI has passed.

**Comment by kenhys** [comment]
I'm working on the WIP branch to clarify the issue.

**Comment by kenhys** [comment]
Rerun yum workflow whether it is reproducible again.

**Comment by kenhys** [comment]
> Rerun yum workflow whether it is reproducible again.

It is not reproducible now with CentOS 7 CI. Hmm...

https://github.com/fluent-plugins-nursery/td-agent-builder/pull/248/checks?check_run_id=1698932744

**Comment by repeatedly** [comment]
@ashie I noticed td-agent 4.1.0 packages is bigger than 4.0.1.
I checked the actual files and `cache` directory includes data.

```
$ du -hs 4.1.0/opt/td-agent/lib/ruby/gems/2.7.0/cache/
19M	4.1.0/opt/td-agent/lib/ruby/gems/2.7.0/cache/
$ du -hs 4.0.1/opt/td-agent/lib/ruby/gems/2.7.0/cache/
0	4.0.1/opt/td-agent/lib/ruby/gems/2.7.0/cache/
```

Could you check this?

**Comment by ashie** [comment]
We should remove also bundler's cache files that are Git origin:

```shell
$ find /opt/td-agent/lib/ruby/gems/2.7.0/cache
/opt/td-agent/lib/ruby/gems/2.7.0/cache
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/description
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/packed-refs
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/config
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/HEAD
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/objects
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/objects/pack
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/objects/pack/pack-54f97fbc9487ccba61a9fd009c4bcd61e93c7fea.idx
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/objects/pack/pack-54f97fbc9487ccba61a9fd009c4bcd61e93c7fea.pack
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/objects/info
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/branches
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/refs
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/refs/tags
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/refs/heads
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/post-update.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/fsmonitor-watchman.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/pre-commit.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/pre-applypatch.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/pre-receive.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/commit-msg.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/pre-push.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/applypatch-msg.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/pre-rebase.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/prepare-commit-msg.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/update.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/hooks/pre-merge-commit.sample
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/info
/opt/td-agent/lib/ruby/gems/2.7.0/cache/bundler/git/fluentd-056552d4882523cb294228ddc312a52e04f7dfe0/info/exclude
```

https://github.com/fluent-plugins-nursery/td-agent-builder/blob/999bd5f39dc74eafc49a95b6a0de4c8f7825e895/td-agent/Rakefile#L983-L987

**Comment by ashie** [comment]
The package size has been reduced (25MB to 12MB) by #256.

**Comment by repeatedly** [comment]
Thanks! I'm now retrying new package build.

**Pull request merged**
