### PR TITLE
deb: add td-agent-apt-source package

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
focal:

```
oot@df0d0169e931:/# apt install /tmp/td-agent-apt-source_2020.8.25-1_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'td-agent-apt-source' instead of '/tmp/td-agent-apt-source_2020.8.25-1_all.deb'
The following additional packages will be installed:
  dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libasn1-8-heimdal libassuan0 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libkrb5-26-heimdal libksba8 libldap-2.4-2 libldap-common libnpth0
  libreadline8 libroken18-heimdal libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.1 libwind0-heimdal pinentry-curses readline-common
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage scdaemon libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql pinentry-doc readline-doc
The following NEW packages will be installed:
  dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libasn1-8-heimdal libassuan0 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libkrb5-26-heimdal libksba8 libldap-2.4-2 libldap-common libnpth0
  libreadline8 libroken18-heimdal libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.1 libwind0-heimdal pinentry-curses readline-common
  td-agent-apt-source
0 upgraded, 33 newly installed, 0 to remove and 0 not upgraded.
Need to get 5687 kB/5692 kB of archives.
After this operation, 17.7 MB of additional disk space will be used
[...]
```
update repository.

```
# apt update
Get:1 http://packages.treasuredata.com/4/ubuntu/focal focal InRelease [7687 B]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease                                                               
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease                         
Get:4 http://packages.treasuredata.com/4/ubuntu/focal focal/contrib amd64 Packages [845 B]
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 8532 B in 1s (9037 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

search 

```
root@df0d0169e931:/# apt search td-agent
Sorting... Done
Full Text Search... Done
td-agent/focal 4.0.1-1 amd64
  Treasure Agent: A data collector for Treasure Data

td-agent-apt-source/now 2020.8.25-1 all [installed,local]
  GnuPG archive key and APT source of the Treasure Agent archive

```

install

```
root@df0d0169e931:/# apt install td-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libyaml-0-2
The following NEW packages will be installed:
  libyaml-0-2 td-agent
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.3 MB of archives.
After this operation, 64.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://packages.treasuredata.com/4/ubuntu/focal focal/contrib amd64 td-agent amd64 4.0.1-1 [11.2 MB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libyaml-0-2 amd64 0.2.2-1 [48.9 kB]
Fetched 11.3 MB in 1s (7751 kB/s)                                     
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libyaml-0-2:amd64.
(Reading database ... 4491 files and directories currently installed.)
Preparing to unpack .../libyaml-0-2_0.2.2-1_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.2.2-1) ...
Selecting previously unselected package td-agent.
Preparing to unpack .../td-agent_4.0.1-1_amd64.deb ...
Unpacking td-agent (4.0.1-1) ...
Setting up libyaml-0-2:amd64 (0.2.2-1) ...
Setting up td-agent (4.0.1-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu
/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr
/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Adding system user `td-agent' (UID 101) ...
Adding new group `td-agent' (GID 101) ...
Adding new user `td-agent' (UID 101) with group `td-agent' ...
Creating home directory `/var/lib/td-agent' ...
Conffile /etc/td-agent/td-agent.conf has been modified. Remain untouched.
Processing triggers for libc-bin (2.31-0ubuntu9) ...
```

**Comment by kenhys** [comment]
buster:

```
root@8ff70202167d:/# apt install /tmp/td-agent-apt-source_2020.8.25-1_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'td-agent-apt-source' instead of '/tmp/td-agent-apt-source_2020.8.25-1_all.deb'
The following additional packages will be installed:
  dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libldap-2.4-2 libldap-common libnpth0
  libreadline7 libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.1 lsb-base pinentry-curses readline-common
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage scdaemon libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql pinentry-doc readline-doc
The following NEW packages will be installed:
  dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libldap-2.4-2 libldap-common libnpth0
  libreadline7 libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.1 lsb-base pinentry-curses readline-common td-agent-apt-source
0 upgraded, 25 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.1 MB/10.1 MB of archives.
After this operation, 22.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```
update

```
root@8ff70202167d:/# apt update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Get:3 http://packages.treasuredata.com/4/debian/buster buster InRelease [7693 B]
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Get:5 http://packages.treasuredata.com/4/debian/buster buster/contrib amd64 Packages [971 B]
Fetched 8664 B in 0s (23.5 kB/s) 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

search

```
root@8ff70202167d:/# apt search td-agent
Sorting... Done
Full Text Search... Done
td-agent/buster 4.0.1-1 amd64
  Treasure Agent: A data collector for Treasure Data

td-agent-apt-source/now 2020.8.25-1 all [installed,local]
  GnuPG archive key and APT source of the Treasure Agent archive

```

install

```
root@8ff70202167d:/# apt install td-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libyaml-0-2
The following NEW packages will be installed:
  libyaml-0-2 td-agent
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 11.3 MB of archives.
After this operation, 64.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 libyaml-0-2 amd64 0.2.1-1 [47.2 kB]
Get:2 http://packages.treasuredata.com/4/debian/buster buster/contrib amd64 td-agent amd64 4.0.1-1 [11.2 MB]
Fetched 11.3 MB in 2s (6592 kB/s)            
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libyaml-0-2:amd64.
(Reading database ... 7035 files and directories currently installed.)
Preparing to unpack .../libyaml-0-2_0.2.1-1_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.2.1-1) ...
Selecting previously unselected package td-agent.
Preparing to unpack .../td-agent_4.0.1-1_amd64.deb ...
Unpacking td-agent (4.0.1-1) ...
Setting up libyaml-0-2:amd64 (0.2.1-1) ...
Setting up td-agent (4.0.1-1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu
/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr
/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Adding system user `td-agent' (UID 101) ...
Adding new group `td-agent' (GID 101) ...
Adding new user `td-agent' (UID 101) with group `td-agent' ...
Creating home directory `/var/lib/td-agent' ...
Conffile /etc/td-agent/td-agent.conf has been modified. Remain untouched.
Processing triggers for libc-bin (2.28-10) ...
```

**Comment by cosmo0920** [comment]
I couldn't get packages....
```log
% rake apt:build
cp /media/Data2/Gitrepo/td-agent-builder/lib/apt/build.sh apt/build.sh
rm -rf apt/tmp
mkdir -p apt/tmp
cp td-agent-apt-source-2020.8.25.tar.gz apt/tmp/td-agent-apt-source-2020.8.25.tar.gz
cd apt
docker build --tag td-agent-apt-source-debian-buster --build-arg DEBUG=yes debian-buster
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM debian:buster
 ---> 378ca4b1d2fe
Step 2/4 : RUN   echo "debconf debconf/frontend select Noninteractive" |     debconf-set-selections
 ---> Using cache
 ---> 95f967e46a6b
Step 3/4 : ARG DEBUG
 ---> Using cache
 ---> 77c7ade30eb1
Step 4/4 : RUN   quiet=$([ "${DEBUG}" = "yes" ] || echo "-qq") &&   apt update ${quiet} &&   apt install -y -V ${quiet}     debhelper     devscripts     gnupg &&   apt clean &&   rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> ddcb5341d27c
Successfully built ddcb5341d27c
Successfully tagged td-agent-apt-source-debian-buster:latest
docker run --rm --tty --volume /media/Data2/Gitrepo/td-agent-builder/td-agent-apt-source/apt:/host:rw --env DEBUG=yes td-agent-apt-source-debian-buster /host/build.sh
cp: cannot stat 'debian/lintian/td-agent/debian.profile': No such file or directory
Failed cp debian/lintian/td-agent/debian.profile /root/.lintian/profiles/td-agent/debian.profile
rake aborted!
Command failed with status (1): [docker run --rm --tty --volume /media/Data...]
/media/Data2/Gitrepo/td-agent-builder/lib/package-task.rb:149:in `run_docker'
/media/Data2/Gitrepo/td-agent-builder/lib/package-task.rb:218:in `block (2 levels) in apt_build'
/media/Data2/Gitrepo/td-agent-builder/lib/package-task.rb:214:in `each'
/media/Data2/Gitrepo/td-agent-builder/lib/package-task.rb:214:in `block in apt_build'
/media/Data2/Gitrepo/td-agent-builder/lib/package-task.rb:213:in `apt_build'
/media/Data2/Gitrepo/td-agent-builder/lib/package-task.rb:246:in `block (2 levels) in define_apt_task'
Tasks: TOP => apt:build
(See full trace by running task with --trace)
```

**Comment by kenhys** [comment]
I've forgotten to commit some files.

**Comment by cosmo0920** [comment]
Adding td-agent-apt-source package CI should be the another PR?

**Review by cosmo0920 — APPROVED** [review]

**Comment by kenhys** [comment]
> Adding td-agent-apt-source package CI should be the another PR?

@cosmo0920  Yes, I'll do it in another PR.

**Pull request merged**
