### PR TITLE
CI: split github test cases

### PR DESCRIPTION
**Pull request by kenhys**
It is easy to recognize which steps are failed.

Closes: #199

### CODE REVIEW

**Comment by cosmo0920** [comment]
Ubuntu Focal and CentOS 6 are stalled on Serverspec testing phase?

**Comment by kenhys** [comment]
It seems they are stalled. ...

**Comment by kenhys** [comment]
On local Docker CentOS 6, It doesn't stall, but causes "Could not locate Gemfile" error.

```

An error occurred while loading ./serverspec/linux/td-agent.rb.
Failure/Error: raise GemfileNotFound, "Could not locate Gemfile or .bundle/ directory" unless bundle_dir
Bundler::GemfileNotFound:
  Could not locate Gemfile or .bundle/ directory
  
# ./serverspec/linux/td-agent.rb:24:in `block in <top (required)>'
# ./serverspec/linux/td-agent.rb:19:in `<top (required)>'
# ------------------
# --- Caused by: ---
# Bundler::GemfileNotFound:
#   Could not locate Gemfile
#   ./serverspec/linux/td-agent.rb:24:in `block in <top (required)>'

Finished in 0.00003 seconds (files took 0.53969 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by kenhys** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/205#issuecomment-692569597　
is caused by missing .bundle.

**Review by cosmo0920 — APPROVED** [review]
LGTM!

**Comment by kenhys** [comment]
Passed except Travis-CI

**Comment by cosmo0920** [comment]
:tada:

**Pull request merged**
