### PR TITLE
Raise an error when package size is increased unexpectedly

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
It seems a bit strange.

```
PS C:\work\td-agent-builder.msi> "{0:0.0} MiB ({1}) {2}" -F ($previous_msi.Length / 1024 / 1024), $previous_msi.Length, $previous_msi.Name | Write-Host
24.0 MiB (25187040) td-agent-4.0.1-x64.msi
PS C:\work\td-agent-builder.msi> "{0:0.0} MiB ({1}) {2}" -F ($msi.Length / 1024 / 1024), $msi.Length, $msi.Name | Write-Host
33.7 MiB (35294249) td-agent-4.1.0-x64.msi
```

**Comment by kenhys** [comment]
Extracted dark.exe && diff result.

[diff.txt](https://github.com/fluent-plugins-nursery/td-agent-builder/files/5929931/diff.txt)

**Comment by kenhys** [comment]
Increased package size is caused by ri documentation.

**Comment by kenhys** [comment]
Windows test case is detected expectedly.

**Comment by ashie** [comment]
> Increased package size is caused by ri documentation.

I'll check whether it can be fixed by #261 or not.

**Comment by kenhys** [comment]
I've rebased because #261 was merged.

**Comment by kenhys** [comment]
I'll expect Windows CI will pass

**Comment by ashie** [comment]
> > Increased package size is caused by ri documentation.
> 
> I'll check whether it can be fixed by #261 or not.

Ah, it's added by RubyInstaller as of 2.7.2-1.

**Comment by ashie** [comment]
> I'll expect Windows CI will pass

I've already checked on my local environment, it doesn't take effect enough.

**Comment by ashie** [comment]
> Increased package size is caused by ri documentation.

Wow, it's includes 16,628 files!

**Comment by ashie** [comment]
It will be fixed by #262.

**Comment by ashie** [comment]
CI succeeded also on windows.

**Pull request merged**
