### PR TITLE
Release 4.1.0 again

### PR DESCRIPTION
**Pull request by repeatedly**
Try to release 4.1.0 again.

### CODE REVIEW

**Comment by repeatedly** [comment]
Now testing built packages...

**Comment by ashie** [comment]
I've added a same commit with #270 to this branch to fix a typo in td-agent.bat.

**Comment by repeatedly** [comment]
I just released td-agent 4.1.0 for rpm/deb.
We decided to postpone msi release for checking in_tail regression on Windows.

**Comment by ashie** [comment]
I merge this PR and add v4.1.0 tag.

> We decided to postpone msi release for checking in_tail regression on Windows.

We are checking failed tests on Windows now.
If it's really broken, we should release it with updated fluentd.
It it's not broken, we should release td-agent for Windows with this tag.

**Comment by ksandrmatveyev** [comment]
> I just released td-agent 4.1.0 for rpm/deb.
> We decided to postpone msi release for checking in_tail regression on Windows.

Hi,

@repeatedly @ashie. Is there any prediction when 4.1.0 will be released for Windows?

Thanks in advance,

**Comment by ashie** [comment]
> We are checking failed tests on Windows now: e.g.) https://ci.appveyor.com/project/fluent/fluentd/builds/37994844
> If it's really broken, we should release it with an updated fluentd.
> It it's not broken, we should release td-agent for Windows with this tag.

Probably it's test's problem.
I'm checking it with https://github.com/fluent/fluentd/pull/3283
It's O.K. to release if the check is passed.

**Comment by ashie** [comment]
> Probably it's test's problem.
> I'm checking it with [fluent/fluentd#3283](https://github.com/fluent/fluentd/pull/3283)
> It's O.K. to release if the check is passed.

Confirmed: https://github.com/ashie/fluentd/runs/2092898427?check_suite_focus=true
We'll prepare td-agent 4.1.0 for Windows.

**Pull request merged**
