### PR TITLE
msi: fix uninstallable binary on non-English

### PR DESCRIPTION
**Pull request by kenhys**
Reported via https://github.com/fluent/fluentd/issues/3322

For example, there is a case that the required account is not created by
non-english platforms. It depends on localization.

Instead, it may be better to use well-known ACEs in SDDL.

ref. https://docs.microsoft.com/en-us/windows/win32/secauthz/security-descriptor-definition-language-for-conditional-aces-

### CODE REVIEW

**Comment by kenhys** [comment]
This PR is not tested.

**Comment by kenhys** [comment]
According to https://github.com/fluent/fluentd/issues/3322#issuecomment-816532142, 
It works without a workaround, so this fix is reasonable.

**Comment by ashie** [comment]
I've added more comments to make easy to understand the curse spells :imp:

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
