### PR TITLE
Fix missing td command in package

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by ashie** [comment]
For linux, it should be done at build time instead of install time because the path is never changed.
On Windows, the install path may be changed by a user, this is why windows installer do it at install time.

**Comment by kenhys** [comment]
Hmm, this approach should be changed.

**Comment by kenhys** [comment]
Changed to use gem pristine correctly during the build process.

**Comment by ashie** [comment]
I confirmed that td and elastic_ruby_console in a built package works correctly.

**Comment by ashie** [comment]
Merged. Thanks!
BTW please consider adding a test for it :)

**Comment by kenhys** [comment]
I'll add a test case in another PR.

**Pull request merged**
