### PR TITLE
Do not install duplicated fluentd under bundler/gems/...

### PR DESCRIPTION
**Pull request by kenhys**
Closes: #263

In the previous versions, fluentd was installed twice.

  /opt/td-agent/lib/ruby/gems/2.7.0/bundler/gems/fluentd-793c9aa3a45b/
  /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-x.y.z

It is obviously redundant, but it is required to avoid "bundle exec
fluentd ...". This kind of redundancy is introduced by git source.

To fix the issue, use two approaches:

* Fixate specific version by git_source (same as the previous way)
* Use pre-built gem and install it from local gem repository (new)

By using the above approach, we can gain benefits (locking
Fluentd version as-is and remove redundancy with fluentd installation)

NOTE: It may be simple to unify source FLUENTD_LOCAL_GEM_REPO but,
source ... syntax requires a full path and it embeds full path into
Gemfile.lock, it is not acceptable because it varies in each build
environment, so it is better to use a pre-built gem and use it (2-pass
approach)

### CODE REVIEW

**Comment by kenhys** [comment]
As a result, bundler/gems was removed.

```
% dpkg-deb -c ./apt/repositories/ubuntu/pool/bionic/universe/t/td-agent/td-agent_4.1.0-1_amd64.deb |\grep bundler/gems
```

**Comment by kenhys** [comment]
It still needs fix.

**Comment by kenhys** [comment]
As bundler/gems directory was removed so it should be changed in /usr/sbin/td-agent.

**Comment by kenhys** [comment]
Although It may be better to ship with 4.1.1, but no need to rush into it. assigned to milestone to 4.2.0.

**Comment by kenhys** [comment]
> error: m4: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is invalid

Hmm, need to check sign.

**Comment by kenhys** [comment]
There is incompatible on WIndows platform, I've fixed it.

**Comment by kenhys** [comment]
> > error: m4: signature from "Alexey Pavlov (Alexpux) [alexpux@gmail.com](mailto:alexpux@gmail.com)" is invalid

It may be resolved in newer CI logs.

**Comment by kenhys** [comment]
It seems weird logs with focal.


```
2021-04-21T05:53:09.5335220Z Segmentation fault (core dumped)
2021-04-21T05:53:09.5341581Z /opt/td-agent/bin/ruby -I/opt/td-agent/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib:/opt/td-agent/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib /opt/td-agent/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern serverspec/linux/\*.rb failed
2021-04-21T05:53:09.5387255Z [1;35m2021-04-21 05:53:09 +0000 [error]: #0 unexpected error error_class=SignalException error="SIGHUP"[0;39m
2021-04-21T05:53:10.2408410Z ##[error]Process completed with exit code 139.
```

**Comment by kenhys** [comment]
> It is not related this PR itself, It seems weird logs with focal.
> 
> ```
> 2021-04-21T05:53:09.5335220Z Segmentation fault (core dumped)
> 2021-04-21T05:53:09.5341581Z /opt/td-agent/bin/ruby -I/opt/td-agent/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.2/lib:/opt/td-agent/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib /opt/td-agent/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern serverspec/linux/\*.rb failed
> 2021-04-21T05:53:09.5387255Z �[1;35m2021-04-21 05:53:09 +0000 [error]: #0 unexpected error error_class=SignalException error="SIGHUP"�[0;39m
> 2021-04-21T05:53:10.2408410Z ##[error]Process completed with exit code 139.
> ```

I'll try to rerun to check reproducibility.

**Comment by kenhys** [comment]
Update explanation in Gemfile.

**Review by ashie — APPROVED** [review]
LGTM

I'll merge it after merging #288.

**Pull request merged**
